### ISSUE TITLE
Lage GUI

### ISSUE THREAD

**Issue by patootey** [patootey/api_oppgave#8]

**Comment by Grocto** [comment]
`import tkinter as tk  # Importerer tkinter-biblioteket for GUI
from PIL import Image, ImageTk  # Importerer moduler for bildebehandling

class Button:
    def __init__(self, root, settings, command_config=None):
        self.clicked = False
        self.button = tk.Button(root, **settings, command=self.click)
        self.command_config = command_config
        self.settings = settings
    
    def click(self):
        self.clicked = True if self.clicked == False else False
        if self.clicked and self.command_config != None:
            self.button.config(**self.command_config)
        else:
            self.button.config(**self.settings)

prevpage = []  # En liste for å lagre tidligere visningskomponenter


# Funksjon for å fjerne alle komponenter unntatt de som er spesifikt angitt i 'page'
def clear_window(root, page=[]):
    for widget in root.winfo_children():
        if widget not in page and widget not in savedWidgets and widget not in prevpage:
            widget.destroy()


# Funksjon for å lagre nåværende visningskomponenter
def keep_page(root):
    page = []
    for widget in root.winfo_children():
        if widget.winfo_ismapped() and widget not in savedWidgets:
            page.append(widget)
            widget.forget()
    return page


# Funksjon for å laste inn tidligere visningskomponenter i 'page'
def load_page(root, page):
    if page is not None:
        clear_window(root, page=page)
        for widget in page:
            widget.pack()


savedWidgets = []  # En liste for å lagre tidligere opprettede komponenter


# Funksjon for å lagre en enkelt widget i 'savedWidgets'
def save_widget(widget):
    global savedWidgets
    savedWidgets.append(widget)



import tkinter as tk
import general as ge


r = tk.Tk()  # Oppretter et hovedvindu (root) for GUI-en
r.title("currency")  # Setter tittelen på vinduet
r.geometry("400x300")  # Setter størrelsen på vinduet til 400x300 piksler




def main(root):
    ge.clear_window(root)  # Kaller en funksjon for å fjerne alle widgets fra vinduet
    button1 = ge.Button(root, {"text":"Søk med Land" , "bg":"white"}, command_config=({"bg":"green"}))
    button1.button.grid(row=1, column=1)
    root.mainloop()  # Starter GUI-hovedløkka for å vise vinduet

main(r)`
